### ISSUE TITLE
"Check out the Wiki" badge for GitHub and GitBook hosted wikis

### ISSUE THREAD

**Issue by Andre601** [intergrav/devins-badges#10]
Perhaps a badge saying "Check out the Wiki" for wikis hosted on GitHub or GitBook could be useful for some?
(I honestly won't need it, but you never know...)

**Comment by wafflecoffee** [comment]
https://github.com/intergrav/devins-badges/blob/main/badges/documentation_64h.png

**Comment by intergrav** [comment]
I'll create some ones for different types of wiki platforms, but yes the generic wiki one also exists
