### ISSUE TITLE
Badges for different platforms (PS5, Switch, etc)

### ISSUE THREAD

**Issue by woodiertexas** [intergrav/devins-badges#11]
Platform badges: Steam, PS5, Xbox Series, Epic Games Store, GOG, itch.io

Optional Fun Badges: Old consoles (such as the Wii, NES, Sega Saturn, Nintendo 64, PS2, Nintendo DS, etc)

**Comment by intergrav** [comment]
added
![image](https://user-images.githubusercontent.com/42325132/190886069-76561bfd-90ad-412b-bd6f-9793948ee3c7.png)

![image](https://user-images.githubusercontent.com/42325132/190886073-a0d44205-944e-483d-90a4-ee467cd7dd47.png)
