### ISSUE TITLE
“Requires Continuity” badge

### ISSUE THREAD

**Issue by osfanbuff63** [intergrav/devins-badges#17]
[Continuity](https://www.curseforge.com/minecraft/mc-mods/continuity) is a re-implementation of OptiFine's CTM for Fabric. CTM (short for Connected Textures Mod), provides a way to connect blocks in a resource pack, as well as emissive textures. Resource packs using these features require this mod to work.

TL;DR we need a Requires Continuity badge xD

**Comment by intergrav** [comment]
Sure! I'll do it once I'm home, which will be in a while.

**Comment by intergrav** [comment]
Working on it now

**Comment by intergrav** [comment]
I changed it to a Connected Textures badge to be in line with the CEM and CIT badges, let me know if you need a continuity badge though

![image](https://user-images.githubusercontent.com/42325132/191631916-12cacce4-97c9-4b47-a00b-bbab85b378dc.png)
