### ISSUE TITLE
More "built with" badges

### ISSUE THREAD

**Issue by intergrav** [intergrav/devins-badges#18]
(Suggested by [@Andre_601](https://github.com/Andre601) on the Modrinth Discord)

-`build-with/`
- [x] #19
- [x] #20
- [x] #21
- [x] #22
- [x] #23

**Comment by Andre601** [comment]
Not sure tbh if it is worth mentioning the Java version and not just "Java" itself.

Also, maybe add Kotlin too for people that are using Kotlin.

**Comment by intergrav** [comment]
starting to work on this now, was publishing npm package (@intergrav/devins-badges)

**Comment by intergrav** [comment]
close to being finished, just got to port it over to compact and minimal badges now

**Comment by intergrav** [comment]
done :) (published to npm aswell)
