### ISSUE TITLE
BuiltByBit and Polymart badges

### ISSUE THREAD

**Issue by Zarkness** [intergrav/devins-badges#26]
Add badge to indicate that you are on the following pages:

BuiltByBit (formerly mc-market)
Polymart

links to both sites:
https://builtbybit.com
https://polymart.org

**Comment by intergrav** [comment]
Will be available in the next release, along with #29

**Comment by intergrav** [comment]
This is what they look like
![image](https://user-images.githubusercontent.com/42325132/193706890-b36134b8-c1d0-441e-967d-9abaab5846e4.png)

**Comment by intergrav** [comment]
Now available in 2.4.0
