### ISSUE TITLE
Available on PyPi

### ISSUE THREAD

**Issue by osfanbuff63** [intergrav/devins-badges#31]
https://pypi.org is the standard for Python packages, so we should probably have a badge that it's available there.

**Comment by intergrav** [comment]
Sure thing

**Comment by intergrav** [comment]
Will be available soon

![image](https://user-images.githubusercontent.com/42325132/194648021-c4395bd0-62bf-44db-9254-9ddf7dd1cc97.png)

**Comment by intergrav** [comment]
forgot to add the label
