### ISSUE TITLE
Musescore, JWPepper, Soundcloud, Spotify [NEW]

### ISSUE THREAD

**Issue by woodiertexas** [intergrav/devins-badges#33]
**What is the badge for?**
Music Sites

**Example if needed**
JWpepper: https://www.jwpepper.com/sheet-music/welcome.jsp
Musescore: https://musescore.com/ , https://musescore.org/

**Comment by intergrav** [comment]
Should it say "Available for" as the top text or something else?

**Comment by intergrav** [comment]
Will be available next release, tomorrow because I had to sleep once I finished these.

All good?

![image](https://user-images.githubusercontent.com/42325132/196595492-54505db3-a9df-4524-8f62-e6bc16fb3a16.png)

**Comment by woodiertexas** [comment]
Sorry about late reply, but yea.

**Comment by intergrav** [comment]
Alright. Also I forgot to release this today sorry about that, I will try to remember tomorrow. Been busy with some things

**Comment by intergrav** [comment]
It's been added to the repo and published to npm, I will update the site very soon
