### ISSUE TITLE
OptiFine badge fix capitalisation [FIX]

### ISSUE THREAD

**Issue by HappiePlant** [intergrav/devins-badges#34]
**Which badge would you like the changes to be applied to?**
The OptiFine badge
**What fix would you like to see applied?**
The capitalisation should be "OptiFine"
**Provide any preferred icons/text (icons must be SVG)**
"Optifine" -> "OptiFine"
**Example if needed**

*I actually don't use OptiFine but I thought this was worth mentioning. I love the badges though.*

**Comment by intergrav** [comment]
Sure thing! I'll do it very soon, should be an easy fix
