### ISSUE TITLE
Additive badge appears to be blurry

### ISSUE THREAD

**Issue by woodiertexas** [intergrav/devins-badges#35]
**Which badge would you like the changes to be applied to?**
Additive Badge

**What fix would you like to see applied?**
Make it not blurry lol

**Provide any preferred icons/text (icons must be SVG)**

**Example if needed**
![image](https://user-images.githubusercontent.com/17211100/197421546-3c10291f-f920-4b3a-84f4-550f9419c836.png)

**Comment by intergrav** [comment]
lol. I think it's because I used the additive logo `.png`, I can fix this tomorrow if I have time. Should be pretty easy
