### ISSUE TITLE
Musescore badge needs some fixing + musescore 4 badge variant

### ISSUE THREAD

**Issue by woodiertexas** [intergrav/devins-badges#39]
**Which badge would you like the changes to be applied to?**
The Musescore badge.

**What fix would you like to see applied?**
Make the "mu" smaller so it isn't touching the circumference of the blue circle.

**Provide any preferred icons/text (icons must be SVG)**
The musescore repo doesn't contain any SVGs of the musescore 3 or 4 icons so chances are you'll have to trace them and turn them into SVGs.

**Example if needed**
Musescore 3 icon: https://github.com/musescore/MuseScore/blob/3.6.2/assets/musescore-icon-round-1024.png

Musescore 4 icon: https://github.com/musescore/MuseScore/blob/master/share/icons/AppIcon/MS4_AppIcon_1024x1024.png

**Comment by intergrav** [comment]
how about this

![image](https://user-images.githubusercontent.com/42325132/199353586-0def0828-ca1b-40ed-a195-2f7640de0250.png)

**Comment by intergrav** [comment]
also, ill just update the current badge as it's easier to manage

**Comment by woodiertexas** [comment]
> how about this
> 
> ![image](https://user-images.githubusercontent.com/42325132/199353586-0def0828-ca1b-40ed-a195-2f7640de0250.png)

looks pretty good, sorry about replying late as i was at school
