### ISSUE TITLE
Badges for Bukkit, Spigot, etc

### ISSUE THREAD

**Issue by Peter-Crawley** [intergrav/devins-badges#4]
bukkit, spigot, paper

**Comment by Andre601** [comment]
Purpur too

And for Proxies: BungeeCord, Waterfall and Velocity.

**Comment by intergrav** [comment]
ill start working on it now that im home

**Comment by intergrav** [comment]
ill work on a couple other ones aswell

**Comment by intergrav** [comment]
i think that looks alright, i got off track so it took a while

![image](https://user-images.githubusercontent.com/42325132/190828538-f345ddb5-29d4-4c68-8ed2-64047fddd74c.png)

**Comment by Andre601** [comment]
Why is paper having this weird colouring as background?
I think a normal grey would be good enough here.

**Comment by intergrav** [comment]
Its the colors on the sides of the logo, ill try just a gray though
![image](https://user-images.githubusercontent.com/42325132/190829506-df92f281-553e-412c-983c-741b83df61e1.png)

**Comment by intergrav** [comment]
Yeah that looks better

![image](https://user-images.githubusercontent.com/42325132/190829549-35cc5a6c-fa99-44fc-9699-f8482ff2c886.png)

I'm going to add a couple more badges for other issues and then push to the repo

**Comment by Andre601** [comment]
> Yeah that looks better
> 
> ![image](https://user-images.githubusercontent.com/42325132/190829549-35cc5a6c-fa99-44fc-9699-f8482ff2c886.png)
> 
> I'm going to add a couple more badges for other issues and then push to the repo

perhaps keep the text also white? Not sure.

**Comment by Andre601** [comment]
Also, on another note, Spigot uses a yellow-orange like colour for their logo and forum theme.
Tho this could kinda clash with Sponge here.

Idk what colour it uses exactly tbh.

**Comment by intergrav** [comment]
Alright I think these look good

![image](https://user-images.githubusercontent.com/42325132/190830598-3cc6352b-406a-4d91-b4ec-a2e0dab32b14.png)

**Comment by intergrav** [comment]
The spigot one might need a bit more work though

**Comment by Andre601** [comment]
The badges look good... Just need to find a way to properly include them without looking bad on my readme.
