### ISSUE TITLE
"Available on CodeMC" badge

### ISSUE THREAD

**Issue by Andre601** [intergrav/devins-badges#41]
**What is the badge for?**
To display dev builds or API being available on [CodeMC.io](https://ci.codemc.io)
Perhaps this can be extended to Jenkins in general? Idk.

**Provide any preferred icons/text (icons must be SVG)**
There is a PNG of the CodeMC logo available (Doesn't look that great in dark theme if you ask me (White outlines)), tho the colour should be changed to red.

There are also AI files available to use, so if you can turn those into SVG, do so.

Link: https://github.com/CodeMC/Documentation/tree/master/docs/assets/img

**Example if needed**

**Comment by intergrav** [comment]
![image](https://user-images.githubusercontent.com/42325132/202830358-0a7588c7-7bda-4824-a559-fa8b613072df.png)

**Comment by intergrav** [comment]
Will be available next release (along with a few other badges) likely tomorrow

**Comment by intergrav** [comment]
Lmk if you need any changes
