### ISSUE TITLE
Check the website badge [NEW]

### ISSUE THREAD

**Issue by CompeyDev** [intergrav/devins-badges#42]
**What is the badge for?**
Similar to read the docs, a visit the website or something similar would be cool.

**Provide any preferred icons/text (icons must be SVG)**
None.

**Example if needed**
None.

**Comment by intergrav** [comment]
Will be available next release, coming sometime soon

![image](https://user-images.githubusercontent.com/42325132/202819695-35e0a3a6-21b5-4818-91ce-9e160a0a4736.png)
