### ISSUE TITLE
Translate on badges [NEW]

### ISSUE THREAD

**Issue by osfanbuff63** [intergrav/devins-badges#45]
**What is the badge for?**
Showing where you can translate the project.

**Provide any preferred icons/text (icons must be SVG)**
Specifically, **Translate on Weblate** and/or **Translate on Crowdin** 

**Example if needed**
*No response*

**Comment by intergrav** [comment]
Should I make a new category for this? Like `translate/`?

**Comment by intergrav** [comment]
Also, would like to make a generic badge - what should the text be?

**Comment by osfanbuff63** [comment]
> Should I make a new category for this? Like `translate/`?

Probably, doesn't really fit into any of the others too well.

> Also, would like to make a generic badge - what should the text be?

Some (potentially refined) version of `Contribute translations` maybe?
