### ISSUE TITLE
Available on deno.land [NEW]

### ISSUE THREAD

**Issue by shateq** [intergrav/devins-badges#46]
**What is the badge for?** 
DENO LAND https://deno.land/x

**Provide any preferred icons/text (icons must be SVG)**
Text: Available on deno.land
Icon (high res and svg): https://raw.githubusercontent.com/denolib/high-res-deno-logo/master/deno_hr_circle.svg

**Example if needed**
I see this in white/black color palette

Have fun creating!

**Comment by intergrav** [comment]
Sure thing? How is this?

![image](https://user-images.githubusercontent.com/42325132/202870689-e89ee456-334b-4fb5-9fad-5bf56c79e9b9.png)

or....

![image](https://user-images.githubusercontent.com/42325132/202870694-6ff7e6dc-72e9-4be0-950c-2d35883fc18b.png)

**Comment by shateq** [comment]
It's great, buddy! 😄 How about an alt version with colors inverted?
