### ISSUE TITLE
Report bugs/suggest features on GitHub [NEW]

### ISSUE THREAD

**Issue by Madis0** [intergrav/devins-badges#51]
**What is the badge for?**
To link to GitHub issues or to a specific issue creator form

**Provide any preferred icons/text (icons must be SVG)**
![github-plural](https://cdn.jsdelivr.net/npm/@intergrav/devins-badges@2/assets/cozy/social/github-plural_vector.svg)

**Example if needed**
![github-plural](https://cdn.jsdelivr.net/npm/@intergrav/devins-badges@2/assets/cozy/social/github-plural_vector.svg)

**Comment by Madis0** [comment]
no u

**Comment by intergrav** [comment]
oops
