### ISSUE TITLE
Review on AlternativeTo [NEW]

### ISSUE THREAD

**Issue by Madis0** [intergrav/devins-badges#52]
**What is the badge for?**

Encouraging users to review their product on [AlternativeTo](https://alternativeto.net)

**Provide any preferred icons/text (icons must be SVG)**

https://alternativeto.net/static/logo.svg

**Example if needed**

N/A

**Comment by Madis0** [comment]
no u

**Comment by Madis0** [comment]
I think "review on" would be better because AlternativeTo doesn't actually "host" anything but the reviews.

**Comment by PSGitHubUser1** [comment]
Well, if you want more badges, check the issues tab. Maybe you'll one more you need??

Btw, im touching grass rn so wait till im back home.

**Comment by PSGitHubUser1** [comment]
Well, take your files...

`AlternativeTo`
- [alt-cozymin.zip](https://github.com/intergrav/devins-badges/files/13615381/alt-cozymin.zip)

- [alt-compactmin.zip](https://github.com/intergrav/devins-badges/files/13615382/alt-compactmin.zip)

- [alt-compact.zip](https://github.com/intergrav/devins-badges/files/13615383/alt-compact.zip)

- [alt-cozy.zip](https://github.com/intergrav/devins-badges/files/13615384/alt-cozy.zip)

**Comment by Madis0** [comment]
Thanks! 
One observation though: I used the alt-compact one and the text doesn't seem to be the same scale as others. [Live example](https://github.com/Fabulously-Optimized/fabulously-optimized#fabulously-optimized)

**Comment by PSGitHubUser1** [comment]
Wait, OH MY GOD! You are the author of Fabulously Optimized Modpack!!!

Damn... Let me try to fix that tho (im still amazed)

**Comment by PSGitHubUser1** [comment]
Wait that looks really bad infront of those colourful badges...
![image](https://github.com/intergrav/devins-badges/assets/90406016/0e00cdeb-5909-49d6-8ac9-fc084aa8c0f2)

Take this instead..

- [howtoinstall.zip](https://github.com/intergrav/devins-badges/files/13618447/howtoinstall.zip)

**Comment by PSGitHubUser1** [comment]
> Okay, thanks 😁 Updated the readme.

You liked both of them... Good to hear that..

**Comment by PSGitHubUser1** [comment]
> Okay, thanks 😁 
> Updated the readme.

Want any more help?

I just noticed that my badge doesn't feel gradient like others in your repo.....

You will also find it out if you look closely.

(btw i want to be a contributor in your repo. I know what can i do to that i guess...?)

**Comment by Madis0** [comment]
> > Okay, thanks 😁
> > Updated the readme.
> 
> Want any more help?
> 
> I just noticed that my badge doesn't feel gradient like others in your repo.....
> 
> You will also find it out if you look closely.
> 
> (btw i want to be a contributor in your repo. I know what can i do to that i guess...?)

Feel free to fix the gradient, post it here and make a direct PR to my repo readme then.
