### ISSUE TITLE
Nukkit / PowerNukkit / PowerNukkitX Badges [NEW]

### ISSUE THREAD

**Issue by IndianBartonka** [intergrav/devins-badges#54]
Like a spigot,bukkit,purpur badages 

https://github.com/PowerNukkit/PowerNukkit

https://github.com/PowerNukkitX/PowerNukkitX

https://github.com/CloudburstMC/Nukkit/blob/master/.github/images/banner.png

**Comment by intergrav** [comment]
Make sure to keep issue #53 in mind :) I'll get them done once I start working on the project then, which I don't exactly know the time that I will

(keep in mind, if needed, you can always make your own badges by downloading the Figma file in the `/other` folder and editing that)

**Comment by IndianBartonka** [comment]
How to open figma file?

**Comment by intergrav** [comment]
Use software called Figma haha (it’s free) https://www.figma.com/

**Comment by intergrav** [comment]
The badge template has some instructions and the other file is the whole devins badges project

**Comment by IndianBartonka** [comment]
Okey thanks
