### ISSUE TITLE
Name of badge, and fix summary [FIX]

### ISSUE THREAD

**Issue by woodiertexas** [intergrav/devins-badges#55]
**Which badge would you like the changes to be applied to?**
Tablesaw badges

**What fix would you like to see applied?**
Updating the mod icon and the badge colors.

**Provide any preferred icons/text (icons must be SVG)**
Tablesaw icon isn't an svg tho

**Example if needed**
![tablesaw](https://user-images.githubusercontent.com/17211100/214176863-2d8ecfc1-03d5-4430-a85c-66bd9426063f.png)

**Comment by woodiertexas** [comment]
Optionally: can make an svg version of the icon

**Comment by intergrav** [comment]
Will be fixed once v3 releases

**Comment by woodiertexas** [comment]
thanks

**Comment by intergrav** [comment]
v3 stuff will be added to the docs soon, but yes this is now fixed
