### ISSUE TITLE
Golang [NEW]

### ISSUE THREAD

**Issue by Huskydog9988** [intergrav/devins-badges#59]
**What is the badge for?**
For project built in golang

**Provide any preferred icons/text (icons must be SVG)**
Built with Go
![Go-Logo_LightBlue](https://user-images.githubusercontent.com/39809509/217981166-6c342f89-3937-4b2d-bfcd-a3353ed198f7.svg)
![gopher](https://user-images.githubusercontent.com/39809509/217981448-92f68495-07ef-451c-91c1-9acae52afb14.svg)

**Example if needed**

**Comment by Huskydog9988** [comment]
That looks awesome! Its far better then I could ever do.

**Comment by PSGitHubUser1** [comment]
> That looks awesome! Its far better then I could ever do.

Oh really? I thought it is decent for like normal use.... 

Thanks for this :)
