### ISSUE TITLE
Spigot/Bukkit download site badges [NEW]

### ISSUE THREAD

**Issue by zax71** [intergrav/devins-badges#61]
Available on Spigot and available on Bukkit badges

![spigot](https://cdn.jsdelivr.net/npm/@intergrav/devins-badges@3/assets/cozy/supported/spigot_vector.svg)
![bukkit](https://cdn.jsdelivr.net/npm/@intergrav/devins-badges@3/assets/cozy/supported/bukkit_vector.svg)
Just changing `for` to `on`

**Comment by PSGitHubUser1** [comment]
Can you provide me that logos

**Comment by zax71** [comment]
It would be in the style of [this Modrinth one](https://github.com/intergrav/devins-badges/blob/v3/assets/cozy/available/modrinth_vector.svg), not sure if that's what you wanted. I can't find the Figma files for those two I linked, so getting the colours is hard to do it myself.

![Modrinth example img](https://raw.githubusercontent.com/intergrav/devins-badges/v3/assets/cozy/available/modrinth_vector.svg)

**Comment by PSGitHubUser1** [comment]
> It would be with the text of [this Modrinth one](https://github.com/intergrav/devins-badges/blob/v3/assets/cozy/available/modrinth_vector.svg), not sure if that's what you wanted. I can't find the Figma files for those two I linked, so getting the colours is hard to do it myself.
> 
> ![Modrinth example img](https://raw.githubusercontent.com/intergrav/devins-badges/v3/assets/cozy/available/modrinth_vector.svg)

I mean i just want the logo of spigot and bukkit... Not the whole image which you liked before... Then i can make that logo (whole) myself

**Comment by zax71** [comment]
Ah! I see, sorry about that. They are attached below

![spigot](https://static.spigotmc.org/img/spigot.png)

![Bukkit](https://i.imgur.com/3UiJTr1_d.webp?maxwidth=1520&fidelity=grand)

**Comment by PSGitHubUser1** [comment]
[bukkit-cozy.zip](https://github.com/intergrav/devins-badges/files/13583250/bukkit-cozy.zip)
[spigot-cozy.zip](https://github.com/intergrav/devins-badges/files/13583251/spigot-cozy.zip)

Take these for now...
