### ISSUE TITLE
Built with Python/Flask [NEW]

### ISSUE THREAD

**Issue by nsde** [intergrav/devins-badges#63]
**What is the badge for?**
Develeopers

**Provide any preferred icons/text (icons must be SVG)**
## Python
https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg
![](https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg)

## Flask (without the text, please!)
https://upload.wikimedia.org/wikipedia/commons/3/3c/Flask_logo.svg
![](https://upload.wikimedia.org/wikipedia/commons/3/3c/Flask_logo.svg)

## SASS
https://upload.wikimedia.org/wikipedia/commons/9/96/Sass_Logo_Color.svg
![](https://upload.wikimedia.org/wikipedia/commons/9/96/Sass_Logo_Color.svg)

**Comment by PSGitHubUser1** [comment]
I can make for python.. but only for `built-with` and `requires` category..

**Comment by PSGitHubUser1** [comment]
I don't if you like them or not, but it is kind of okayish to me...
`Flask`
[flask-compact.zip](https://github.com/intergrav/devins-badges/files/13538964/flask-compact.zip)
[flask-compactmin.zip](https://github.com/intergrav/devins-badges/files/13538965/flask-compactmin.zip)
[flask-cozy.zip](https://github.com/intergrav/devins-badges/files/13538966/flask-cozy.zip)
[flask-cozymin.zip](https://github.com/intergrav/devins-badges/files/13538968/flask-cozymin.zip)

`'SASS'`
[sass-compact1.zip](https://github.com/intergrav/devins-badges/files/13538974/sass-compact1.zip)
[sass-compactmin.zip](https://github.com/intergrav/devins-badges/files/13538975/sass-compactmin.zip)
[sass-cozy1.zip](https://github.com/intergrav/devins-badges/files/13538976/sass-cozy1.zip)
[sass-cozymin.zip](https://github.com/intergrav/devins-badges/files/13538977/sass-cozymin.zip)

`'Sass'`
[sass-compact2.zip](https://github.com/intergrav/devins-badges/files/13538978/sass-compact2.zip)
[sass-cozy2.zip](https://github.com/intergrav/devins-badges/files/13538979/sass-cozy2.zip)
