### ISSUE TITLE
Built on Fabulously Optimized icon

### ISSUE THREAD

**Issue by osfanbuff63** [intergrav/devins-badges#7]
Thanks for making this! Since we have a 'built on Simply Optimized' badge, we should have a 'built on Fabulously Optimized' badge too, as there's so many Fabric packs nowadays building upon it.

**Comment by intergrav** [comment]
Sure! I'll begin working on it now.

**Comment by intergrav** [comment]
I think this looks fine

![image](https://user-images.githubusercontent.com/42325132/190833744-43e22c05-2deb-4ebe-9d52-be225c4afb10.png)

**Comment by intergrav** [comment]
![image](https://user-images.githubusercontent.com/42325132/190834182-a7174b93-8dc7-4b5e-8d51-bc99438d99ac.png)

made it dark instead to fit the other badges, this will be out soon but i'm gonna do a few more badges
