### ISSUE TITLE
"Review on MMC Reviews" [NEW]

### ISSUE THREAD

**Issue by CalaMariGold** [intergrav/devins-badges#75]
[https://mmcreviews.com/](https://mmcreviews.com/)

![34792_Modded Minecraft Reviews Logo_Logomark Primary cropped](https://github.com/intergrav/devins-badges/assets/57605926/0f9653e4-5f2f-4d86-880d-caad62ca7c05)
![34792_Modded Minecraft Reviews Logo_Logomark Primary No BG cropped](https://github.com/intergrav/devins-badges/assets/57605926/2513c748-37a6-4d26-9467-747f3a92b0bb)

Thanks!

**Comment by CalaMariGold** [comment]
If you need any other assets lmk!

**Comment by PSGitHubUser1** [comment]
Devin is on break, I feel like I am managing this repo by making new badges lol...

Well, I am making this badge jw.

**Comment by PSGitHubUser1** [comment]
Does this satisfy your needs?
I think it looks really bad..

## Compact
- [compact-min-mmc.zip](https://github.com/intergrav/devins-badges/files/13888276/compact-min-mmc.zip)
- [compact-mmc.zip](https://github.com/intergrav/devins-badges/files/13888277/compact-mmc.zip)

## Cozy
- [cozy-min-mmc.zip](https://github.com/intergrav/devins-badges/files/13888279/cozy-min-mmc.zip)
- [cozy-mmc.zip](https://github.com/intergrav/devins-badges/files/13888280/cozy-mmc.zip)

**Comment by CalaMariGold** [comment]
From the perspective of someone who isn't a designer, I think it looks great! I don't really see what you mean by the logo itself not being aligned

**Comment by PSGitHubUser1** [comment]
> From the perspective of someone who isn't a designer, I think it looks great! I don't really see what you mean by the logo itself not being aligned

No.. Like it is not a pefect star like the bottom one smaller than upper one... (the badge itself is cutted from bottom side.. It took a lot of effort to align it with badge..
