### ISSUE TITLE
Visit the Website [NEW]

### ISSUE THREAD

**Issue by PSGitHubUser1** [intergrav/devins-badges#76]
## Description
I made another badge after #73 and it looks more like 'Website', I know you made a one before but if you ask me, it's like a Document.. doesn't give feeling of "Website".. that's why I made this.

### Cozy
[cozy-website.zip](https://github.com/intergrav/devins-badges/files/13888805/cozy-website.zip)
[cozy-min-website.zip](https://github.com/intergrav/devins-badges/files/13888806/cozy-min-website.zip)
### Compact
[compact-website.zip](https://github.com/intergrav/devins-badges/files/13888807/compact-website.zip)
[compact-min-website.zip](https://github.com/intergrav/devins-badges/files/13888808/compact-min-website.zip)

**Comment by intergrav** [comment]
I just replaced the original website icon with a link icon from Lucide

**Comment by PSGitHubUser1** [comment]
Uhh wdym by this? Can you explain
