### ISSUE TITLE
Categorize badges and maybe preview page?

### ISSUE THREAD

**Issue by Andre601** [intergrav/devins-badges#8]
It could be useful to put the images/SVGs into separate folders based on what they are for.

f.e. `spigot` or `plugins` containing the badges for platforms supported or `downloads` for badges about where you can download them from.

As an example: `badges/downloads/modrinth_vector.svg`

----

Another thing that could be nice to add is a page to preview the badges. Something like a `PREVIEW.md` that would display the badges and also show their Markdown-code to use.
Would allow people to more easily know what badges look like.

If wanted can I work on this myself and PR it later on.

**Comment by intergrav** [comment]
This may break some of the badges people are currently using, but I could give it a try. Maybe I'll keep a legacy badges folder, and then have a new assets folder which is the one that should be used.

**Comment by intergrav** [comment]
Should this be counted as documentation? Or moved somewhere else.

![image](https://user-images.githubusercontent.com/42325132/190873668-534359ba-5478-4734-be77-bed4ef998f59.png)

**Comment by intergrav** [comment]
This is what I have done for organization

![image](https://user-images.githubusercontent.com/42325132/190873767-c3b0e21e-6779-46e7-9f68-b228a60bb93e.png)

**Comment by Andre601** [comment]
> This may break some of the badges people are currently using, but I could give it a try. Maybe I'll keep a legacy badges folder, and then have a new assets folder which is the one that should be used.

Maybe use GitHub pages for this?
Like have the new badges on a github.io domain while keeping the old ones where they are right now.
Another alternative would be to create a new branch as the default to use while putting the current one as a separate branch. That way should image links remain the same, while you can provide a new format.

> Should this be counted as documentation? Or moved somewhere else.
> 
> ![image](https://user-images.githubusercontent.com/42325132/190873668-534359ba-5478-4734-be77-bed4ef998f59.png)

Would say it counts towards documentation, yeah.

**Comment by intergrav** [comment]
I think going the github pages way works out, because I was going to make a website for this anyway (not a picker though)
