### ISSUE TITLE
OptiNa Team Badge [NEW]

### ISSUE THREAD

**Issue by NotAGanesh** [intergrav/devins-badges#81]
**What is the badge for?**
---
The badge serves as a professional symbol representing your team of modpack developers. It signifies your collective achievements, expertise, and contributions in the field. Just like a badge worn with pride, it showcases your team’s dedication, creativity, and commitment to creating exceptional modpacks for the community. Keep up the great work! 🌟👏

**Provide any preferred icons/text (icons must be SVG)**
---
**compact**
![compact_vector](https://github.com/intergrav/devins-badges/assets/105713980/6c352a6c-693d-4b27-b538-0c5dc1e863db)

**compact-minimal**
![optina-team_vector](https://github.com/intergrav/devins-badges/assets/105713980/35b5212f-0c05-4f92-8055-2dc17306bab0)

**cozy**
![cozy_vector](https://github.com/intergrav/devins-badges/assets/105713980/fba153c8-8b3c-44f4-aba8-a9df4b77e65d)

**cozy minimal**
![cozy-minimal_vector](https://github.com/intergrav/devins-badges/assets/105713980/0b016cdd-8f14-4a00-91a5-941792791c47)

**Example if needed**
---
i needed for my modpack readme

**Comment by rowandevving** [comment]
I don't really see who else would use this badge other than your team, and you are always free to use badges based off the badge template in your own projects anyway.

**Comment by intergrav** [comment]
Personally I think that, since this is meant for your team and not public use, you should host this badge elsewhere such as an organization or project repository. As @rowandevving said, you may use and host badges you make from the badge template freely.

**Comment by NotAGanesh** [comment]
> A real Ganesh wouldn't use AI to write PRs, @NotAGanesh 😄

sometimes when you feel so lazy lol
