### ISSUE TITLE
Cleanroom Loader(Forge 1.12.2 fork) support please [NEW]

### ISSUE THREAD

**Issue by Oganesson897** [intergrav/devins-badges#83]
**What is the badge for?**
Some projects build on Clenaroom.
like forge mods, but cleanroom.

**Provide any preferred icons/text (icons must be SVG)**
![Icon](https://cleanroommc.com/cleanroom.png)

**Example if needed**

**Comment by rowandevving** [comment]
Probably just worth making your own badge with the figma template, if you read the README.

**Comment by Oganesson897** [comment]
ok ic thanks you
